language: ruby
rvm:
  - jruby-9.0.0.0.pre1
gemfile:
  - Gemfile
services:
  - redis-server
  - rabbitmq
addons:
  firefox: "17.0"
env:
  - DB=postgresql
before_install:
  - cd www
script:
  - cd www
  - RAILS_ENV=test bundle exec rake --trace db:migrate:reset
  - jruby --dev -S bundle exec rspec spec/models/* -fd
  - cd ..
  - ./nodeinstall.sh
  - cd handlr
  - source npminstall.sh
  - mocha
before_script:
  - mkdir tmp/cache
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database gamerist_test' -U postgres
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd ..

