language: ruby
rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - www/Gemfile
env:
  - DB=postgresql
before_script:
  - cd www
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database gamerist_test' -U postgres
matrix:
  include:
    - rvm: jruby-19mode
      gemfile: www/Gemfile_java
