language: ruby
rvm:
  - jruby-9.0.0.0.pre1
gemfile:
  - Gemfile
services:
  - redis-server
  - rabbitmq
addons:
  firefox: "17.0"
env:
  - DB=postgresql
before_install:
  - cd www
script:
<<<<<<< HEAD
  - RAILS_ENV=test bundle exec rake --trace db:migrate:reset
  - ./www/smart_rspec.sh
=======
  - ./smart_rspec.sh
  - bundle exec rspec -f d --drb
>>>>>>> f6d9402a371f2c84aadfc4ff12543f9a1417adfe
  - cd ..
  - ./nodeinstall.sh
  - cd handlr
  - source npminstall.sh
  - mocha
before_script:
  - mkdir tmp/cache
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database gamerist_test' -U postgres
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
