language: ruby
rvm:
  - jruby-19mode
gemfile:
  - Gemfile
services:
  - redis-server
  - rabbitmq
env:
  - DB=postgresql
before_install:
  - cd www
  - mkdir tmp
  - mkdir tmp/cache
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate:reset
  - jruby --ng-server &
  - jruby --ng -S spork &
  - ./smart_spec.sh
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database gamerist_test' -U postgres
