language: ruby
rvm:
  - 1.9.3
env:
  - DB=postgres
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
gemfile:
  - Gemfile_test
before_script:
  - psql -e 'create database gamerist_test'
