// Generated by CoffeeScript 1.4.0
(function() {
  var Config, amqp, connection, fs, nedb;

  amqp = require('amqp');

  nedb = require('nedb');

  fs = require('fs');

  Config = JSON.parse(fs.readFileSync('./config.json', 'utf8'));

  connection = amqp.createConnection({
    host: Config.rabbitmq.url
  });

  connection.on('ready', function() {
    return console.log("READY");
  });

}).call(this);
