web:
  build: .
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db
    - redis
    - rabbitmq
db:
  image: library/postgres:9.4.4
  ports:
    - "13306:3306"
redis:
  image: redis
rabbitmq:
  image: rabbitmq

