source 'https://rubygems.org'
ruby '2.2.0', :engine => 'jruby', :engine_version => '9.0.0.0.pre1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.2' # 4.2.1

# PostgreSQL
group :development, :production do
  gem 'activerecord-jdbcpostgresql-adapter', '1.3.7', require: false
end

gem 'connection_pool'

# Use SCSS for stylesheets
gem 'sass-rails'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'execjs', require: false
gem 'therubyrhino', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-cdn', '1.10.2'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
#gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

gem 'activeadmin', github: 'activeadmin'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
  gem 'yard', require: false
end

# Gamerist-specific
gem 'devise' #, "~> 3.4.1" # 3.2.4
gem 'omniauth'
gem 'omniauth-steam'
gem 'paypal-sdk-rest', require: false # 0.6.1
gem 'geocoder', require: false # 1.2.0
gem 'json_vat', github: 'adamcooke/json-vat', ref: 'dba4172', require: false
gem 'google_currency', require: false

gem 'rack-cache', require: false
gem 'redis', require: false # 3.0.7
gem 'redis-rails', require: false # 4.0.0
gem 'mlanett-redis-lock', require: 'redis-lock'

gem "bunny", require: false
#gem "march_hare", require: false

gem 'ejs', require: 'ejs'
gem 'annotate', require: false
gem 'agis', require: false
gem 'sinatra', require: false

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

gem 'puma', '2.11.2', require: false

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

# group :development do
#  gem 'spork'
#  gem 'guard-rspec', require: false
# end

group :development, :test do
  gem 'activerecord-jdbcsqlite3-adapter', '1.3.7', require: false
  gem 'rspec', require: false
  gem 'rspec-rails', require: false
  gem 'capybara', require: false
  gem 'factory_girl_rails', require: false
  gem 'coveralls', require: false
  gem 'database_cleaner', require: false
  gem 'mocha', require: false
  gem 'require_all'#, require: false
  gem 'selenium-webdriver', require: false
end

group :production do
  gem 'newrelic_rpm'
end
