source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

# PostgreSQL
gem 'activerecord-jdbcpostgresql-adapter'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'execjs'
gem 'therubyrhino', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

gem 'activeadmin', github: 'gregbell/active_admin'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Gamerist-specific
gem 'devise'
gem 'omniauth'
gem 'omniauth-steam'
gem 'net-ssh'
gem 'paypal-sdk-rest'
gem 'geocoder'

gem 'redis'
gem 'redis-rails'
gem 'rack-cache'
gem 'march_hare'

gem 'ejs', require: 'ejs'
gem 'rails-backbone'
gem 'annotate'
gem 'sidekiq'
gem 'sinatra', require: false

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

gem 'puma'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

group :development do
  gem 'spork'
  gem 'guard-rspec', require: false
end

group :test do
  gem 'activerecord-jdbcsqlite3-adapter'
  gem 'rspec', require: false
  gem 'rspec-rails', require: false
  gem 'capybara', require: false
  gem 'selenium-webdriver', require: false
  gem 'factory_girl_rails', require: false
  gem 'coveralls', require: false
  gem 'database_cleaner', require: false
  gem 'mocha', require: false
  gem 'require_all'#, require: false
end
