$GAMERIST_MODIFIERS = Hash.new

$GAMERIST_MODIFIERS["MARGIN_MULT_PRETTY"] = 16
$GAMERIST_MODIFIERS["ROOM_WAGER_MIN"] = 5
$GAMERIST_MODIFIERS["ROOM_WAGER_MAX"] = 50
$GAMERIST_MODIFIERS["FIXED_WITHDRAWAL_FEE"] = 1
