---
- threecode: SWE
  twocode: SE
  name: Sweden
- threecode: EST
  twocode: ET
  name: Estonia
- threecode: BEL
  twocode: BE
  name: Belgium
- threecode: BGR
  twocode: BG
  name: Bulgaria
- threecode: CZE
  twocode: CZ
  name: Czech Republic
- threecode: DNK
  twocode: DK
  name: Denmark
- threecode: DEU
  twocode: DE
  name: Germany
- threecode: IRL
  twocode: IE
  name: Ireland
- threecode: GRC
  twocode: EL
  name: Greece
- threecode: ESP
  twocode: ES
  name: Spain
- threecode: FRA
  twocode: FR
  name: France
- threecode: HRV
  twocode: HR
  name: Croatia
- threecode: ITA
  twocode: IT
  name: Italy
- threecode: CYP
  twocode: CY
  name: Cyprus
- threecode: LVA
  twocode: LV
  name: Latvia
- threecode: LTU
  twocode: LT
  name: Lithuania
- threecode: LUX
  twocode: LU
  name: Luxembourg
- threecode: HUN
  twocode: HU
  name: Hungary
- threecode: MLT
  twocode: MT
  name: Malta
- threecode: NLD
  twocode: NL
  name: Netherlands
- threecode: AUT
  twocode: AT
  name: Austria
- threecode: POL
  twocode: PL
  name: Poland
- threecode: PRT
  twocode: PT
  name: Portugal
- threecode: ROU
  twocode: RO
  name: Romania
- threecode: SVN
  twocode: SI
  name: Slovenia
- threecode: SVK
  twocode: SK
  name: Slovakia
- threecode: FIN
  twocode: FI
  name: Finland
- threecode: GBR
  twocode: UK
  name: United Kingdom

