---
- name: Other
  twocode: RX
  currency: EUR
  eu: 0
- threecode: EST
  twocode: EE
  name: Estonia
  currency: EUR
  eu: 1
- threecode: SWE
  twocode: SE
  name: Sweden
  currency: SEK
  eu: 1
- threecode: BEL
  twocode: BE
  name: Belgium
  currency: EUR
  eu: 1
- threecode: BGR
  twocode: BG
  name: Bulgaria
  currency: BGN
  eu: 1
- threecode: CZE
  twocode: CZ
  name: Czech Republic
  currency: CZK
  eu: 1
- threecode: DNK
  twocode: DK
  name: Denmark
  currency: DKK
  eu: 1
- threecode: DEU
  twocode: DE
  name: Germany
  currency: EUR
  eu: 1
- threecode: IRL
  twocode: IE
  name: Ireland
  currency: EUR
  eu: 1
- threecode: GRC
  twocode: EL
  name: Greece
  currency: EUR
  eu: 1
- threecode: ESP
  twocode: ES
  name: Spain
  currency: EUR
  eu: 1
- threecode: FRA
  twocode: FR
  name: France
  currency: EUR
  eu: 1
- threecode: HRV
  twocode: HR
  name: Croatia
  currency: HRK
  eu: 1
- threecode: ITA
  twocode: IT
  name: Italy
  currency: EUR
  eu: 1
- threecode: CYP
  twocode: CY
  name: Cyprus
  currency: EUR
  eu: 1
- threecode: LVA
  twocode: LV
  name: Latvia
  currency: EUR
  eu: 1
- threecode: LTU
  twocode: LT
  name: Lithuania
  currency: EUR
  eu: 1
- threecode: LUX
  twocode: LU
  name: Luxembourg
  currency: EUR
  eu: 1
- threecode: HUN
  twocode: HU
  name: Hungary
  currency: HUF
  eu: 1
- threecode: MLT
  twocode: MT
  name: Malta
  currency: EUR
  eu: 1
- threecode: NLD
  twocode: NL
  name: Netherlands
  currency: EUR
  eu: 1
- threecode: AUT
  twocode: AT
  name: Austria
  currency: EUR
  eu: 1
- threecode: POL
  twocode: PL
  name: Poland
  currency: PLN
  eu: 1
- threecode: PRT
  twocode: PT
  name: Portugal
  currency: EUR
  eu: 1
- threecode: ROU
  twocode: RO
  name: Romania
  currency: RON
  eu: 1
- threecode: SVN
  twocode: SI
  name: Slovenia
  currency: EUR
  eu: 1
- threecode: SVK
  twocode: SK
  name: Slovakia
  currency: EUR
  eu: 1
- threecode: FIN
  twocode: FI
  name: Finland
  currency: EUR
  eu: 1
- threecode: GBR
  twocode: GB
  name: United Kingdom
  currency: GBP
  eu: 1
- threecode: USA
  twocode: US
  name: United States
  currency: USD
  eu: 0
- threecode: CAN
  twocode: CA
  name: Canada
  currency: CAD
  eu: 0
- threecode: AUS
  twocode: AU
  name: Australia
  currency: AUD
  eu: 0
- threecode: JPN
  twocode: JP
  name: Japan
  currency: JPY
  eu: 0
- threecode: KOR
  twocode: KR
  name: Republic of Korea
  currency: KRW
  eu: 0
- threecode: NOR
  twocode: "NO"
  name: Norway
  currency: NOK
  eu: 0
- threecode: RUS
  twocode: RU
  name: Russia
  currency: RUB
  eu: 0
- threecode: CHE
  twocode: CH
  name: Switzerland
  currency: CHF
  eu: 0
- threecode: ISL
  twocode: IS
  name: Iceland
  currency: ISK
  eu: 0
- threecode: MEX
  twocode: MX
  name: Mexico
  currency: MXN
  eu: 0
- threecode: TWN
  twocode: TW
  name: Republic of China
  currency: TWD
  eu: 0
- threecode: NZL
  twocode: NZ
  name: New Zealand
  currency: NZD
  eu: 0
- threecode: IND
  twocode: IN
  name: India
  currency: INR
  eu: 0
- threecode: HKG
  twocode: HK
  name: Hong Kong
  currency: HKD
  eu: 0
- threecode: MAC
  twocode: MO
  name: Macau
  currency: MOP
  eu: 0
- threecode: CHN
  twocode: CN
  name: China
  currency: CNY
  eu: 0
- threecode: SRB
  twocode: RS
  name: Serbia
  currency: RSD
  eu: 0
- threecode: TUR
  twocode: TR
  name: Turkey
  currency: TRY
  eu: 0
  
