---
games:
  - name: team fortress 2
    maps: 
      - {name: ctf_2fort, winmode: normal, timelimit: limited, playerlimit: ctf}
      - {name: cp_dustbowl, winmode: red, timelimit: unlimited, playerlimit: none}
      - {name: cp_5gorge, winmode: normal, timelimit: limited, playerlimit: none}
  - name: counter strike source
    maps:
      - {name: de_dust, winmode: normal, timelimit: unlimited, playerlimit: none, rounds: 11}
      - {name: cs_office, winmode: normal, timelimit: unlimited, playerlimit: none, rounds: 11}

