test: &default

  # Credentials for New APIs
  client_id: AV4lGBB0twjUtkL7uJ2fkUjtUznWzb9QyexJeaLJV9AXKcRQ5n3F00tJdly6
  client_secret: EAbDQxAKVcIew8bnIShscCU4-xqE3lm-ckRu1fN8pIRwjSj4fKkPFwVcC4cz

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  app_id: APP-80W284485P519543T
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
