# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0789823e3174c9000d7e4f898e8cc67d2d5a243fde8364b899b358aa67034f32a2f23c6d68617761a9a7f26ac3922d883df1fc2ecfc6cc614696db570f1552f

test:
  secret_key_base: bd3d79ef04f3fa7cb7c3c78a69c9d8a60a29b64641427d69723b8efc61e467d7bc1b342bea755f72f9fa7c744567b8fbc709a370e02b9496b4710dd8bde024a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
